# Generated by Django 3.2.5 on 2021-07-23 13:05

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('phone', models.CharField(max_length=15, null=True)),
                ('company', models.CharField(max_length=32)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonMediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_media', models.ImageField(max_length='256', upload_to='persons')),
                ('media_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.personmediatype')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('cpf_new', cpf_field.models.CPFField(max_length=14, verbose_name='cpf_new')),
                ('cpf_old', cpf_field.models.CPFField(max_length=14, null=True, verbose_name='cpf_old')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.persontype'),
        ),
    ]
